### PR TITLE
Fix errors since v0.19.13

### LINKED ISSUE #93: PlutoSliderServer broken since Pluto v0.19.13
I started trying PlutoSliderServer today and had problems making it work even with small simple notebook due to the following error:
image

This seem to be caused by https://github.com/fonsp/Pluto.jl/pull/2300 which has been merged since v0.19.13

I was surprised that installing PlutoSliderServer would download Pluto v0.19.14 as the compat seems to speciy v0.19.10:
https://github.com/JuliaPluto/PlutoSliderServer.jl/blob/29e98741cf3d2e22acaab18106a253ab58cef7ea/Project.toml#L36-L38

But then I realized that that compat entry does not limit patch release updates.

### PR DESCRIPTION
**Pull request by disberd**
Fixes #93

### CODE REVIEW

**Comment by rikhuijzer** [comment]
Ah this must have been introduced by https://github.com/fonsp/Pluto.jl/pull/2300 then. Specifically by:
```diff
- function Base.convert(::Type{<:Dict}, patch::ReplacePatch)
- 	Dict{String,Any}("op" => "replace", "path" => patch.path, "value" => patch.value)
- end
```
In hindsight, it would have been better to not do https://github.com/fonsp/Pluto.jl/pull/2300 because I recently learned that it's bad for developers to be busy working around the compiler.

Anyway, the PR looks good to me. Thanks for the fix. I'll leave it up to @fonsp to merge since I'm not familiar with `PlutoSliderServer.jl` enough.

**Review by rikhuijzer — APPROVED** [review]

**Comment by disberd** [comment]
Yeah I noticed that the code change was related to that PR while trying to debug the error, but the fix seems likely very easy

**Comment by rikhuijzer** [comment]
> but the fix seems likely very easy

Yeah well it involves a call to `_convert` which is by Julia convention a private method. Making public doesn't make really sense either because `PlutoSliderServer` would be the only user.

With that, I don't mean to say that there is anything wrong with this PR though! This is probably the best solution there is! The problem is in hindsight with https://github.com/fonsp/Pluto.jl/pull/2300.

**Comment by fonsp** [comment]
Thanks, I added https://github.com/fonsp/Pluto.jl/commit/c93b4d267f2b125088b5a618bce29e32d0153cb9 which would have caught the breaking change of https://github.com/fonsp/Pluto.jl/pull/2300

**Pull request merged**
