### PR TITLE
 fix unescaped '/' in URI

### PR DESCRIPTION
**Pull request by behinger**
hashes with "/" are wrongfully cut into parts.

This fix clues the substrings back together. It has two requirements though that we need confirmation by @fonsp though: 
1) If the "payload" exists, it is always in parts[end]
2) the notebookhash always ends with "=" AND no other sub-string (split by '/') of the URI ends with "="

Addresses #46 #42 #45, but instead of changing server configuration as #46, this fixes it within PlutoSliderServer - #46 indicates an issue with "+" as well - but we could not replicate it.

fixed together with @llips

### CODE REVIEW

**Comment by Pat-Laub** [comment]
Thanks! Re: #45, I tried adding this patch on top of the [static-export-1](https://github.com/JuliaPluto/PlutoSliderServer.jl/tree/static-export-1) branch and that 404 problem still appears.

It did make me realise that the URI's were being escaped twice though, which was the problem over there.
That is, for notebook hash `7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs=` 

``` javascript
encodeURIComponent("7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs=")
"7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs%3D"
```
and
``` javascript
encodeURIComponent(encodeURIComponent("7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs="))
"7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs%253D"
```

which corresponds to Deno needing
`http://localhost:8000/bondconnections/7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs%3D`

whereas the Python server needed
`http://localhost:8000/bondconnections/7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs%253D`

How to proceed, though, I'm not sure.

Is there simply a way to create hashes which doesn't use special characters that need escaping in a URL?
E.g. is it possible to just use the filename of the notebook instead of a hash of the contents?

**Comment by fonsp** [comment]
Thanks for looking into this! I'll get back to you very soon, January was a bit too busy for me 😅

**Comment by fonsp** [comment]
Hey @behinger ! Thanks for starting this topic! Let me say that it is *awesome* that you are using PlutoSliderServer, that you were able to fork and fix this on your own, and that you opened a PR to share your fix with the community!!

I think the solution in this PR does not catch all cases, and we still need to think about the problems with URI escaping the other character: `+` (and `=` for padding). I started working on the underlying problem in 

I worked on this today, see https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/57

**Comment by behinger** [comment]
Thanks for the warm words! You can close this PR then. 

@llips noticed a similar problem when using precompute slider server; we fixed it by providing our own Pluto.jl frontend code: https://github.com/llips/Pluto.jl/commit/e1c8a52211d90d2001f923bd0f9dcafdb2c7392b (the option to do so was not very visible in any documentation, but I understand it is a not-ready-yet-PR & a lot of work. kudos!)
I guess this is the right time to mention this, if you need a more detailed report we can do that too.

Happy to share the outcomes of our work, we (mostly Luis) used the precompute PR successfully; needed some further tweaking in some details. Hope to be able to share it soon

**Comment by fonsp** [comment]
Hey @behinger !

I would love any feedback you can give about using the precompute PR! My main question is: what is it like to develop notebooks that will be precomputed? Do you often write notebooks with too many possibilities? How do you know about this, and how do you solve it?

Would you recommend others to use it? Any tips you would give to people who want to start using it?

Thanks again! -fons

**Comment by fonsp** [comment]
Fixed by #57

**Pull request closed without merging**
